@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
set "BACKEND_DIR=%SCRIPT_DIR%API"
set "FRONTEND_DIR=%SCRIPT_DIR%WebUI"
set "RN_DIR=%SCRIPT_DIR%NativeAppUI"
set "ENV_FILE=%SCRIPT_DIR%.env"
set "RN_CONFIG_FILE=%RN_DIR%\generatedLocalConfig.js"

:: ── Detect local IP ───────────────────────────────────────────────────────────
set "LOCAL_IP="
for /f "tokens=2 delims=:" %%A in ('ipconfig ^| findstr /i "IPv4"') do (
    if not defined LOCAL_IP set "LOCAL_IP=%%A"
)
for /f "tokens=* delims= " %%A in ("%LOCAL_IP%") do set "LOCAL_IP=%%A"

if not defined LOCAL_IP (
    echo.
    echo ERROR: Could not detect a local IP address.
    echo Make sure you are connected to WiFi and try again.
    echo.
    pause
    exit /b 1
)

echo [config] Detected IP: %LOCAL_IP%

:: ── Write .env (Vite only — Flask reads API\.env separately) ──────────
(
    echo VITE_LOCAL_DEV=true
    echo VITE_LOCAL_IP=%LOCAL_IP%
    echo LOCAL_IP=%LOCAL_IP%
) > "%ENV_FILE%"

:: ── Write NativeAppUI\generatedLocalConfig.js ─────────────────────────────────────
(
    echo // Auto-generated by start-all.bat -- do not edit.
    echo module.exports = { LOCAL_BASE_URL: 'http://%LOCAL_IP%:5050' };
) > "%RN_CONFIG_FILE%"

echo [config] Written %ENV_FILE% and %RN_CONFIG_FILE%

:: ── Launch all three in separate terminals ────────────────────────────────────
start "utility-tools - Backend" cmd /k "cd /d "%BACKEND_DIR%" && python backend.py"
start "utility-tools - Web Frontend" cmd /k "cd /d "%FRONTEND_DIR%" && npm run dev -- --host"
start "utility-tools - Expo (RN)" cmd /k "cd /d "%RN_DIR%" && npx expo start"

echo.
echo Started Backend, Web Frontend, and Expo in separate terminals.
echo Web:    http://%LOCAL_IP%:5173
echo Phone:  scan QR in the Expo terminal (same WiFi required).
echo.
