// Auto-generated by start-dev.sh on every local dev launch - do not edit.
// Falls back to production URL when not in a local dev session.
let LOCAL_BASE_URL = null;
try {
    // eslint-disable-next-line import/no-unresolved
    const generated = require('./generatedLocalConfig.js');
    LOCAL_BASE_URL = generated.LOCAL_BASE_URL || null;
} catch (_) {}

export const BASE_URL = LOCAL_BASE_URL || 'https://utility-tools-b6dj.onrender.com';
